import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://app.thetestingacademy.com/playwright/ttacart/');
    await expect(page.locator('h1')).toContainText('TTACart');
    await page.locator('[data-test="username"]').click();
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').click();
    await page.locator('[data-test="password"]').fill('tta_secret');
    await page.locator('[data-test="login-button"]').click();
    await expect(page.locator('[data-test="title"]')).toBeVisible();
    await expect(page.locator('[data-test="title"]')).toContainText('Products');
    await expect(page.locator('[data-test="item-test-allthethings-tshirt-red-title-link"]')).toContainText('Test.allTheThings() T-Shirt (Red)');
    await page.locator('[data-test="add-to-cart-test-allthethings-tshirt-red"]').click();
    await page.locator('[data-test="shopping-cart-link"]').click();
    await page.locator('[data-test="checkout"]').click();
    await page.locator('[data-test="firstName"]').click();
    await page.locator('[data-test="firstName"]').fill('yash');
    await page.locator('[data-test="lastName"]').click();
    await page.locator('[data-test="lastName"]').fill('jain');
    await page.locator('[data-test="postalCode"]').click();
    await page.locator('[data-test="postalCode"]').fill('462024');
    await page.locator('[data-test="continue"]').click();
    await expect(page.locator('[data-test="inventory-item-price"]')).toContainText('$15.99');
    await expect(page.locator('[data-test="total-label"]')).toContainText('Total: $17.27');
    await page.locator('[data-test="finish"]').click();
    await expect(page.locator('[data-test="complete-header"]')).toContainText('Thank you for your order!');
    await expect(page.locator('[data-test="complete-text"]')).toContainText('Your order has been dispatched, and will arrive just as fast as the TTA Express pony can get there!');
    await expect(page.locator('[data-test="back-to-products"]')).toBeVisible();
    await page.locator('[data-test="back-to-products"]').click();
});